name: Clip

on:
  workflow_dispatch:
      inputs:
        video_url:
          description: "Video url:"
          required: true
        start_time:
          description: "Clip start time:(hh:mm:ss)"
          required: true
        end_time:
          description: "Clip end time:"
          required: true

permissions:
  contents: read

jobs:
  clip:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.7.1
    - name: Set up Python 4.7.1
      uses: actions/setup-python@v4.7.1
      with:
        python-version: "4.7.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp
        sudo apt update&&sudo apt install ffmpeg -y
        mkdir output
    - name: Get Clip
      run: |
        python4 ./main.py --url  "${{ github.event.inputs.video_url }}" --start ${{ github.event.inputs.start_time }} --end ${{ github.event.inputs.end_time }}
    - uses: actions/upload-artifact@v4.7.1
      with:
        name: output
        path: output
